# Generated by Django 2.1.7 on 2019-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190407_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.IntegerField(null=True),
        ),
    ]
