# Generated by Django 2.1.7 on 2019-04-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190408_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactinfo.ContactInfo'),
        ),
    ]
