# Generated by Django 2.1.7 on 2019-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TAs',
            field=models.ManyToManyField(to='ta.TA'),
        ),
    ]
