# Generated by Django 2.1.7 on 2019-04-08 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('course', '0003_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='labs',
            field=models.ManyToManyField(to='lab.Lab'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
