# Generated by Django 2.1.7 on 2019-04-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190408_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='TAs',
        ),
    ]
