# Generated by Django 2.1.7 on 2019-04-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0002_ta_account'),
        ('course', '0005_remove_course_tas'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TAs',
            field=models.ManyToManyField(to='ta.TA'),
        ),
    ]
