# Generated by Django 2.0.7 on 2019-03-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thingy',
        ),
    ]
