# Generated by Django 2.1.7 on 2019-04-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graderStatus', models.BooleanField()),
                ('numberOfLabs', models.IntegerField()),
            ],
        ),
    ]
