# Generated by Django 2.1.7 on 2019-04-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graderStatus', models.BooleanField()),
                ('numberOfLabs', models.IntegerField()),
                ('account', models.ForeignKey(default='123', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Users')),
            ],
        ),
    ]
