# Generated by Django 2.1.7 on 2019-04-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0002_ta_account'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='TAs',
            field=models.ManyToManyField(to='ta.TA'),
        ),
    ]
